name: todo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.2
  cloud_firestore: ^4.9.3
  collection: ^1.17.2
  crypto: ^3.0.3
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  freezed: ^2.4.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.3.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  rxdart: ^0.27.7
  sticky_headers: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  auto_route_generator: ^7.3.1
  flutter_gen_runner: ^5.3.2

flutter_gen:
  output: lib/generated/
  
  integrations:
    flutter_svg: true  

flutter:
  uses-material-design: true

  assets:
    - assets/icons/